# This allows it to run on faster containers.
sudo: false

language: python

matrix:
  include:
    - python: 2.7
      env: MATPLOTLIB_VERSION=1.5.3 DISPLAY=:99.0
    - python: 3.5
      env: MATPLOTLIB_VERSION=1.5.3 DISPLAY=:99.0
#  allow_failures:
#    - python: "nightly"

addons:
  apt:
    packages:
    - gcc
    - gfortran
    # Deps for matplotlib, can remove once 1.5.0 is released and installable via conda
    - inkscape
    - libav-tools
    - gdb
    - mencoder
    - dvipng
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-latex-recommended
    - graphviz

# To be able to run plotting tests
before_install:
  - sh -e /etc/init.d/xvfb start

# See http://conda.pydata.org/docs/travis.html
install:
  # You may want to periodically update this, although the conda update
  # conda line below will keep everything up-to-date.
  # This saves us some downloading for this version
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Should match requirements.txt
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas pytest
  - source activate test-environment

  - pip install git+https://github.com/matplotlib/matplotlib.git@v$MATPLOTLIB_VERSION;

  # Build in place so we can run tests
  - pip install python-coveralls pytest-cov
  - pip install .
# command to run tests
script: py.test -s --cov=lifelines -vv --block=False --cov-report term-missing
after_success:
  coveralls
# Don't want notifications
notifications:
  email: false
